kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: web
  name: web-privileged
rules:
- apiGroups: [""]
  resources: ["pods", "pods/portforward", "pods/log", "pods/exec"]
  verbs: ["get", "list", "create"]
