kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: port-foward-binding
  namespace: web
subjects:
# G Suite Google Group
- kind: User
  name: dani.scarpa@darknet.fyi
- kind: User
  name: gard.clausen@darknet.fyi
roleRef:
  kind: Role
  name: port-foward
  apiGroup: rbac.authorization.k8s.io
