kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: web
  name: port-foward
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
