kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-privileged-binding
  namespace: web
subjects:
- kind: User
  name: konrad.steele@darknet.fyi
roleRef:
  kind: Role
  name: web-privileged
  apiGroup: rbac.authorization.k8s.io
