kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-reader-binding
  namespace: web
subjects:
- kind: User
  name: devs@darknet.fyi
roleRef:
  kind: Role
  name: web-reader
  apiGroup: rbac.authorization.k8s.io
