kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resources-least-privilege
  namespace: monitoring
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["delete"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list", "describe"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resources-least-privilege
  namespace: monitoring
subjects:
  - kind: Group
    name: devops@darknet.fyi
roleRef:
  kind: Role
  name: resources-least-privilege
  apiGroup: rbac.authorization.k8s.io
