bases:
  - system/flux
  - system/preemptible-killer  
    # TODO not ready yet
    #- system/cert-manager  
    #- system/cert-manager-certificates  
    #- system/vault-secrets-operator
  - monitoring
  - elastic-system
  - logging 
  - guestbook
