apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  replicas: 1 
  resources:
    requests:
      cpu: 10m
      memory: 500Mi
    limits:
      memory: 1Gi
  retention: 4d


