apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../kustomize-base/monitoring

patchesStrategicMerge:
  - alertmanager-alertmanager.yaml 
  - prometheus-prometheus.yaml
