apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  replicas: 1 
  resources:
    requests:
      cpu: 20m
      memory: 800Mi
    limits:
      memory: 2Gi
  retention: 12d

