---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: pod-security-policy-monitoring-20191112221328
spec:
  allowedHostPaths:
  - pathPrefix: /proc
    readOnly: true
  - pathPrefix: /sys
    readOnly: true
  - pathPrefix: /
    readOnly: true
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  hostPID: true
  readOnlyRootFilesystem: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - emptyDir
  - hostPath
  - secret
  - persistentVolumeClaim
  - configMap
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - pod-security-policy-monitoring-20191112221328
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: monitoring
  - kind: ServiceAccount
    name: prometheus-adapter
    namespace: monitoring
  - kind: ServiceAccount
    name: node-exporter
    namespace: monitoring
  - kind: ServiceAccount
    name: kube-state-metrics
    namespace: monitoring
  - kind: ServiceAccount
    name: alertmanager-main
    namespace: monitoring
  - kind: ServiceAccount
    name: grafana
    namespace: monitoring
