---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: star-dev-darknet-fyi
  namespace: web
spec:
  secretName: star-dev-darknet.fyi
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
  - '*.dev.darknet.fyi'
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - '*.dev.darknet.fyi'
