resources:
  - frontend-deployment.yaml
  - frontend-service.yaml
  - namespace.yaml
  - redis-master-deployment.yaml
  - redis-master-service.yaml
  - redis-slave-deployment.yaml
  - redis-slave-service.yaml

