---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: devops
spec:
  chart:
    repository: https://ricoberger.github.io/helm-charts
    name: vault-secrets-operator
    version: 1.3.2
  values:
    vault:
      address: "https://vault.darknet.fyi"
      authMethod: "kubernetes"
      kubernetesPath: "auth/kubernetes"
      kubernetesRole: "vault-secrets-operator"
      reconciliationTime: "300"
    fullnameOverride: "vault-secrets-operator"
    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
    nodeSelector:
      workload: default 
    tolerations:
      - effect: NoSchedule
        key: workload
        operator: Equal
        value: default
