---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: web
spec:
  values:
    nodeSelector:
      preemptible: "true"
      workload:
    tolerations:
