kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devops-admin-binding 
  namespace: devops
subjects:
- kind: User
  name: sander.hvas@darknet.fyi 
roleRef:
  kind: Role
  name: devops-admin 
  apiGroup: rbac.authorization.k8s.io

