kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logstash7-admin-binding 
  namespace: logstash7
subjects:
- kind: User
  name: sander.hvas@darknet.fyi 
roleRef:
  kind: Role
  name: logstash7-admin 
  apiGroup: rbac.authorization.k8s.io
