kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-admin-binding 
  namespace: monitoring
subjects:
# G Suite Google Group
- kind: User
  name: sander.hvas@darknet.fyi 
roleRef:
  kind: Role
  name: monitoring-admin 
  apiGroup: rbac.authorization.k8s.io
