kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-admin-binding 
  namespace: web
subjects:
- kind: User
  name: sander.hvas@darknet.fyi
roleRef:
  kind: Role
  name: web-admin 
  apiGroup: rbac.authorization.k8s.io
