apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gke-preemptible-killer
  labels:
    app: gke-preemptible-killer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gke-preemptible-killer
subjects:
- kind: ServiceAccount
  name: gke-preemptible-killer
  namespace: devops