---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: systems@darknet.fyi
    privateKeySecretRef:
      name: letsencrypt-issuer
    dns01:
      providers:
      - name: route53
        route53:
          region: eu-west-1
          accessKeyID: AKIAIZNYVM6JMMAILTCQ
          secretAccessKeySecretRef:
            name: letsencrypt-aws
            key: secretAccessKey
