apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../kustomize-base/system/cert-manager/
- letsencrypt-aws-secret.yaml
- namespace.yaml
patches:
- helmrelease.yaml
namespace: cert-manager
