apiVersion: v1
kind: Service
metadata:
  name: alertmanager-main
  namespace: monitoring
  annotations:
    beta.cloud.google.com/backend-config: '{ "default": "alertmanager-main" }'
spec:
  type: NodePort