apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistent-storage-pvc
  namespace: monitoring
  labels:
    team: devops
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi