{
 "title": "Kubernetes - DNS",
 "description": "Dashboard for Kubernetes kube-dns service that uses SkyDNS",
 "tags": [
  "K8s",
  "DNS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(skydns_skydns_dns_cachemiss_count_total, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "50% 95% 99% DNS requests MS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(skydns_skydns_dns_request_duration_seconds_bucket[1m])) by (le,system)) * 1000",
     "legendFormat": "50% {{ system }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(skydns_skydns_dns_request_duration_seconds_bucket[1m])) by (le,system)) * 1000",
     "legendFormat": "95% {{ system }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(skydns_skydns_dns_request_duration_seconds_bucket[1m])) by (le,system)) * 1000",
     "legendFormat": "99% {{ system }}"
    }
   ]
  },
  {
   "title": "Cachemiss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(skydns_skydns_dns_cachemiss_count_total{pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Count Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(skydns_skydns_dns_error_count_total{pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} {{system}}"
    }
   ]
  },
  {
   "title": "Request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(skydns_skydns_dns_request_count_total{pod=~\"$pod\"}[1m]) ",
     "legendFormat": "{{pod}} {{system}}"
    }
   ]
  },
  {
   "title": "Avg Request Duration Milliseconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(skydns_skydns_dns_request_duration_seconds_sum{pod=~\"$pod\"}[1m])) by (system) * 1000",
     "legendFormat": "{{system}}"
    }
   ]
  }
 ]
}
{
 "title": "Resource Lifecycle Cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodepool",
    "label": "nodepool",
    "query": "label_values(kube_node_labels, node) "
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Node Pool Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Node Pool Saturation",
     "type": "graph",
     "description": "Percentage of the actual used CPU summed on all nodes from the same pool",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(sum(  label_replace(  rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name=~\"^.+\", node=~\"^($nodepool)-[a-z0-9]*-[a-z0-9]*\"}[1m]),\"nodepool\", \"$1\", \"node\", \"(.*)-[a-z0-9]*-[a-z0-9]*\") ) by (nodepool) * 100 ) \n/\n(sum(  label_replace(  kube_node_status_capacity_cpu_cores{},\"nodepool\", \"$1\", \"node\", \"(.*)-[a-z0-9]*-[a-z0-9]*\")) by (nodepool))",
       "legendFormat": "{{ nodepool }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Nodes Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Saturation",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name=~\"^.+\", node=~\"^($nodepool)-[a-z0-9]*-[a-z0-9]*\"}[1m])) by (node) * 100 )  /  (sum(kube_node_status_capacity_cpu_cores{}) by (node))",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Container Requested Saturation ON Node Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Container Requested Saturation ON Node Pool",
     "type": "graph",
     "description": "Value is a sum of all containers of the same type running in all nodes. \n\n100% => the containers are using the same amount as stated in\n\"resources:     requests:  cpu: (value)m\". \n\n125%  => Containers overutilization  of 25%\n\n60% => Containers underutilization of 40%",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum( label_replace(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name=~\"^.+\", node=~\"^($nodepool)-[a-z0-9]*-[a-z0-9]*\" }[1m]),\n                    \"nodepool\", \"$1\", \"node\", \"(.*)-[a-z0-9]*-[a-z0-9]*\") \n) by (container_name, nodepool)\n   * 100\n/\nsum(  \n  label_replace(     \n        label_replace( kube_pod_container_resource_requests_cpu_cores{node=~\"^($nodepool)-[a-z0-9]*-[a-z0-9]*\"} ,\n                       \"container_name\", \"$1\", \"container\", \"(.*)\"),\n        \"nodepool\", \"$1\", \"node\", \"(.*)-[a-z0-9]*-[a-z0-9]*\")\n) by (container_name, nodepool)",
       "legendFormat": "{{container_name}} --- {{nodepool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Container Actual Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container actual CPU utilisation",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\", container_name=~\"^.+\"}[10m])) by (container_name)",
       "legendFormat": "{{container_name}} -- all pools"
      },
      {
       "expr": "sum(label_replace( rate(container_cpu_usage_seconds_total{container_name!=\"POD\", node=~\"^($nodepool)-[a-z0-9]*-[a-z0-9]*\"}[10m])\n ,\"nodepool\", \"$1\", \"node\", \"(.*)-[a-z0-9]*-[a-z0-9]*\")\n ) by (container_name, nodepool)",
       "legendFormat": "{{container_name}} -- {{nodepool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Node Pool Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Node Pool Saturation",
     "type": "graph",
     "description": "Percentage of the actual used memory summed on all nodes from the same pool",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(\n    label_replace( container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\", node=~\"^($nodepool)-[a-z0-9]*-[a-z0-9]*\"}, \n    \"nodepool\", \"$1\", \"node\", \"(.*)-[a-z0-9]*-[a-z0-9]*\"))  \nby (nodepool)\n  * 100\n/\nsum(  label_replace(  kube_node_status_allocatable_memory_bytes{},\"nodepool\", \"$1\", \"node\", \"(.*)-[a-z0-9]*-[a-z0-9]*\")   ) \nby (nodepool)",
       "legendFormat": "{{nodepool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Node Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Memory Saturation",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(\n    label_replace( container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\", node=~\"^($nodepool)-[a-z0-9]*-[a-z0-9]*\"}, \n    \"nodepool\", \"$1\", \"node\", \"(.*)-[a-z0-9]*-[a-z0-9]*\"))  \nby (node,nodepool)\n  * 100\n/\nsum(  label_replace(kube_node_status_allocatable_memory_bytes{},\"nodepool\", \"$1\", \"node\", \"(.*)-[a-z0-9]*-[a-z0-9]*\")   ) \nby (node, nodepool)",
       "legendFormat": "{{node}} -- {{nodepool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Container Requested Saturation ON Node Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Container Requested Saturation ON Node Pool",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(\n  label_replace(  container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\", node=~\"^($nodepool)-[a-z0-9]*-[a-z0-9]*\"}, \n                  \"nodepool\", \"$1\", \"node\", \"(.*)-[a-z0-9]*-[a-z0-9]*\")\n) by (container_name, nodepool) \n   * 100\n/\nsum(\n  label_replace(  \n    label_replace( kube_pod_container_resource_requests_memory_bytes{},\n                  \"container_name\", \"$1\", \"container\", \"(.*)\") , \n    \"nodepool\", \"$1\", \"node\", \"(.*)-[a-z0-9]*-[a-z0-9]*\")\n) by (container_name, nodepool)",
       "legendFormat": "{{container_name}}  -- {{nodepool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Container Actual Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Actual Memory Usage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\"}) by (container_name)",
       "legendFormat": "{{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "POD Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "POD Count",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_info{}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Resource Lifecycle Deployments",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" },
   {
    "name": "deployment",
    "label": "deployment",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\"}, pod) "
   },
   {
    "name": "container",
    "label": "container",
    "query": "label_values(kube_pod_container_status_running{namespace=~\"$namespace\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\" }, container) "
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment Deviation CPU & MEM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Deployment per Container Saturation",
     "type": "graph",
     "description": "Deviation:  % of the actual usage compared to the requested value \n\nAVERAGE: On Selected TIME WINDOW. Actual average usage in m. This value changes when time window is changed.\n\nREQUESTED:   The value present in deployment as m resources:   requests:  cpu: (value)m",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{container_name!=\"POD\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\" , container_name=~\"$container\"}[1m])\n) by (container_name) * 100 \n/\navg(\n  label_join(kube_pod_container_resource_requests_cpu_cores{ namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container=~\"$container\"},\n  \"container_name\", \"\", \"container\")\n) by (container_name)\n-100",
       "legendFormat": "Deviation ---- {{container_name}} ---------------- %"
      },
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{container_name!=\"POD\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\" , container_name=~\"$container\"}[1m])\n) by (container_name) * 1000",
       "legendFormat": "ACTUAL --- {{container_name}}  (value)m"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests_cpu_cores{ namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container=~\"$container\"}\n) by (container) * 1000",
       "legendFormat": "REQUESTED {{container}} (value)m"
      }
     ]
    },
    {
     "title": "Memory Deployment per Container Saturation",
     "type": "graph",
     "description": "Deviation:  % of the actual usage compared to the requested value \n\nAVERAGE: On Selected TIME WINDOW. Actual average usage in Mi. This value changes when time window is changed.\n\nREQUESTED:   The value present in deployment as Mi resources:   requests:  memory: (value)Mi \nWARNING, for JOBS the avg is not the value in the deployment. Please consult the value in the graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container_name=~\"$container\"}\n) by (container_name) * 100 \n/\navg(label_join(kube_pod_container_resource_requests_memory_bytes{namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container=~\"$container\"},\n   \"container_name\", \"\", \"container\")\n) by (container_name) - 100",
       "legendFormat": "Deviation ---- {{container_name}} ---------------- %"
      },
      {
       "expr": "avg(container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container_name=~\"$container\"}\n/ 1024 / 1024 ) by (container_name)",
       "legendFormat": "ACTUAL --- {{container_name}}  (value)Mi"
      },
      {
       "expr": "avg(label_join(kube_pod_container_resource_requests_memory_bytes{namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container=~\"$container\"},\n   \"container_name\", \"\", \"container\")\n/ 1024 / 1024) by (container_name) ",
       "legendFormat": "REQUESTED {{container_name}} (value)Mi"
      }
     ]
    },
    {
     "title": "Container Actual memory Utilisation ( Expensive query )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\", namespace=~\"($namespace).*\", pod_name=~\"$deployment.*\", container_name=~\"$container\"}\n/ 1024 / 1024",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployment Rollover Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Replicaset hash",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace( kube_pod_status_phase{namespace=~\"($namespace).*\", pod=~\"($deployment-[a-z0-9]*-[a-z0-9]*$|$deployment-[0-9]*$).*\"},     \"rs\", \"$1\", \"pod\", \".*-(.*)-[a-z0-9]{5}$\")) by (rs)",
       "legendFormat": "$deployment-{{rs}}-*"
      }
     ]
    },
    {
     "title": "ENDPOINTS Count - Selected by SERVICE label=$deployment  LB",
     "type": "graph",
     "description": "kubectl get endpoints $deployment",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "kube_endpoint_address_available{namespace=~\"($namespace).*\", endpoint=~\"$deployment.*\"}",
       "legendFormat": "LB -{{endpoint}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployment PODs Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Actual POD Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"($namespace).*\", pod=~\"($deployment-[a-z0-9]*-[a-z0-9]*$|$deployment-[0-9]*$).*\"})",
       "legendFormat": "PODS"
      }
     ]
    },
    {
     "title": "POD Container Delay ( startup / shutdown )",
     "type": "graph",
     "description": "If Container in pods have different start time, they can be present here as not overlapping line",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "count(container_cpu_usage_seconds_total{container_name!=\"POD\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\"}) by (container_name)",
       "legendFormat": "{{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU per Deployment sum of all pods and containers",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none", "label": "m" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name=~\"^.+\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\"}[1m])) * 1000",
       "legendFormat": "USED"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\"}) * 1000",
       "legendFormat": "REQUESTED"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Deployment per Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU per Container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none", "label": "m" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name=~\"^.+\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container_name=~\"$container\"}[1m])) by (container_name) * 1000",
       "legendFormat": "USED ---------- {{container_name}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{ namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container=~\"$container\"}) by (container) * 1000",
       "legendFormat": "REQUESTED {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Deployment per Container RECOMMENDED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recommended Requested CPU per Container ( 6h average -10% )",
     "type": "graph",
     "description": "REQUESTED - The value added in the deployment .yaml for that container. Reflects deployment changes\n\n\n\nACTUAL - Average usage of all running instances of that container. THIS hides anomalies of single containers.\n\n\nRECOMMENDED - Actual usage -10% average on 6 hours. IT is not a static value as that will hide the peaks and lows. This is present as a hint of the expected value",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none", "label": "m" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name=~\"^.+\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\" , container_name=~\"$container\"}[6h]) * 0.90) by (container_name) * 1000 \n/\nsum(label_replace(  kube_pod_container_status_running{ namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container=~\"$container\"} ,\"container_name\", \"$1\", \"container\", \"(.*)\")) by (container_name)",
       "legendFormat": "RECOMMENDED {{container_name}}   ---  requests: cpu: (value)m"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", resource=\"cpu\", container=~\"$container\"}) by (container) * 1000 ",
       "legendFormat": "REQUESTED -- {{container}}"
      },
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container_name=~\"$container\"}[3h])) by (container_name)  ) \n     * 1000 \n/\nsum(\n  label_join(kube_pod_container_status_running{container_name!=\"POD\", namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container=~\"$container\"}, \n             \"container_name\", \"\", \"container\")\n) by (container_name)",
       "legendFormat": "ACTUAL {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "POD Memory utilisation sum of all pods and containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\"})",
       "legendFormat": "Requested"
      }
     ]
    },
    {
     "title": "MEMORY NODE Distribution",
     "type": "graph",
     "description": "This shows that the kubernetes scheduler spawned the pods across multiple nodes or tainting selection forced the placement of too many on one node",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\", namespace=~\"($namespace).*\", pod_name=~\"($deployment-[a-z0-9]*-[a-z0-9]*$|$deployment-[0-9]*$).*\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Deployment per Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory per Container sum of all pods",
     "type": "graph",
     "description": "The values are a sum of all the pods for that deployment. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container_name=~\"$container\"}) by (container_name)",
       "legendFormat": "USED ---------- {{container_name}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{ namespace=~\"($namespace).*\" ,pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container=~\"$container\"}) by (container)",
       "legendFormat": "REQUESTED {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Deployment per Container RECOMMENDED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Deployment per Container RECOMMENDED (6h average usage + 25%)",
     "type": "graph",
     "description": "REQUESTED - The value added in the deployment .yaml for that container. Reflects deployment changes\n\n\n\nACTUAL - Average usage of all running instances of that container. THIS hides anomalies of single containers.\n\n\nRECOMMENDED - Actual usage +25% average on 6 hours. IT is not a static value as that will hide the peaks and lows. This is present as a hint of the expected value",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none", "label": "Mi" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\", namespace=~\"($namespace).*\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container_name=~\"$container\"}\n) by (container_name) \n  * 1.25\n  / 1048576\n/\nsum(\n  label_replace(kube_pod_container_status_running{ namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\"} ,\"container_name\", \"$1\", \"container\", \"(.*)\")\n) by (container_name)",
       "legendFormat": "RECOMMENDED {{container_name}}   ---  requests:  memory: (value)Mi"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests_memory_bytes{ namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container=~\"$container\"}) by (container) \n/ 1048576",
       "legendFormat": "REQUESTED ------ {{container}}"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",container_name=~\"^.+\", namespace=~\"$namespace\", pod_name=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\", container_name=~\"($container).*\"}) by (container_name)\n  / 1048576\n/\nsum(label_replace(  kube_pod_container_status_running{ namespace=~\"($namespace).*\", pod=~\"$deployment-([a-z0-9]{5,10}-[a-z0-9]{5}$|[0-9]{1}$)$\"} ,\"container_name\", \"$1\", \"container\", \"(.*)\")) by (container_name)",
       "legendFormat": "ACUTAL ------------- {{container_name}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Thanos Sidecar",
 "tags": [ "thanos" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(thanos_build_info, job)"
   }
  ]
 },
 "panels": [
  { "title": "Thanos Sidecar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Upload time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(thanos_objstore_bucket_last_successful_upload_time{job=\"$job\"})*1000"
    }
   ]
  },
  {
   "title": "Last Heartbeat time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(thanos_sidecar_last_heartbeat_success_time_seconds{job=\"$job\"})*1000"
    }
   ]
  },
  {
   "title": "Query RPS [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$job\"}[$interval])) by (grpc_code, grpc_method, pod)",
     "legendFormat": "{{grpc_code}} {{grpc_method}}  {{pod}}"
    }
   ]
  },
  {
   "title": "Query Response Time Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\"}[$interval])) by (grpc_method, le, pod))",
     "legendFormat": "99.99 {{grpc_method}} {{pod}}"
    }
   ]
  },
  {
   "title": "Bucket Operations/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{job=\"$job\"}[$interval])) by (pod, operation)",
     "legendFormat": "{{operation}} {{pod}}"
    }
   ]
  },
  {
   "title": "Bucket Operation Failures/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_failures_total{job=\"$job\"}[$interval])) by (operation,pod)",
     "legendFormat": "{{operation}} {{pod}}"
    }
   ]
  },
  {
   "title": "Bucket Operation Time Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{job=\"$job\"}[$interval])) by (pod,le))",
     "legendFormat": "99.99 bucket ops {{pod}}"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\"}",
     "legendFormat": "{{quantile}} {{pod}}"
    },
    {}
   ]
  }
 ]
}
{
 "title": "Thanos Store",
 "tags": [ "thanos" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "labelselector", "query": "service" },
   { "name": "labelvalue", "query": "thanos-store-gateway" },
   {
    "name": "service",
    "query": "label_values(thanos_build_info, service)"
   },
   {
    "name": "pod",
    "query": "label_values(thanos_build_info, pod) "
   }
  ]
 },
 "panels": [
  { "title": "thanos-store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query RPS [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (grpc_code, grpc_method, pod)",
     "legendFormat": "{{grpc_code}} {{grpc_method}}  {{pod}}"
    }
   ]
  },
  {
   "title": "Response Time 99.99 Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(grpc_server_handling_seconds_bucket{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (grpc_method, le, pod))",
     "legendFormat": "{{grpc_method}} {{pod}}"
    }
   ]
  },
  {
   "title": "Response Size 99.99 Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (le, pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Operations/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod, operation)",
     "legendFormat": "bucket {{operation}} {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_drops_total{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "block drops {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_loads_total{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "block loads {{pod}}"
    }
   ]
  },
  {
   "title": "Operation Failures/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_failures_total{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (operation,pod)",
     "legendFormat": "bucket {{operation}} {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_drop_failures_total{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "block drop {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_load_failures_total{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "block load {{pod}}"
    }
   ]
  },
  {
   "title": "Operation Time Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod,le, operation))",
     "legendFormat": "99.99 bucket {{operation}} {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod,le))",
     "legendFormat": "99.99 get all {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_series_merge_duration_seconds_bucket{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod,le))",
     "legendFormat": "99.99 merge {{pod}}"
    }
   ]
  },
  {
   "title": "Cache Ops/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_store_index_cache_items_added_total{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod,item_type)",
     "legendFormat": "added {{item_type}} {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_store_index_cache_items_evicted_total{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod,item_type)",
     "legendFormat": "evicted {{item_type}} {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_store_index_cache_requests_total{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod,item_type)",
     "legendFormat": "requests {{item_type}} {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_store_index_cache_hits_total{$labelselector=\"$labelvalue\", pod=\"$pod\"}[$interval])) by (pod, item_type)",
     "legendFormat": "hits {{item_type}} {{pod}}"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{$labelselector=\"$labelvalue\", pod=\"$pod\"}",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{$labelselector=\"$labelvalue\", pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{$labelselector=\"$labelvalue\", quantile=\"1\", pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Thanos Query",
 "tags": [ "thanos" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(thanos_build_info, pod)"
   },
   { "name": "labelvalue", "query": "thanos-query" },
   { "name": "labelselector", "query": "service" }
  ]
 },
 "panels": [
  { "title": "Thanos Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{$labelselector=\"$labelvalue\"}[$interval])) by (pod, grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}} {{grpc_method}} {{pod}}"
    }
   ]
  },
  {
   "title": "Response Time Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(grpc_client_handling_seconds_bucket{$labelselector=\"$labelvalue\"}[$interval])) by (grpc_method,pod, le))",
     "legendFormat": "99.99 {{grpc_method}} {{pod}}"
    }
   ]
  },
  {
   "title": "Thanos Query 99.99 Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(http_request_duration_seconds_bucket{$labelselector=\"$labelvalue\",handler=\"query\"}[$interval])) by (pod, le))",
     "legendFormat": "instant_query {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(http_request_duration_seconds_bucket{$labelselector=\"$labelvalue\",handler=\"query_range\"}[$interval])) by (pod, le))",
     "legendFormat": "range_query {{pod}}"
    }
   ]
  },
  {
   "title": "Prometheus Query 99 Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "thanos_engine_query_duration_seconds{$labelselector=\"$labelvalue\",quantile=\"0.99\"}  ",
     "legendFormat": " {{slice}} {{pod}}"
    }
   ]
  },
  {
   "title": "Prometheus Queries/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_queries{$labelselector=\"$labelvalue\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{$labelselector=\"$labelvalue\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{$labelselector=\"$labelvalue\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{$labelselector=\"$labelvalue\"}",
     "legendFormat": "{{quantile}} {{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Thanos Compactor",
 "tags": [ "thanos" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "labelselector", "query": "service" },
   { "name": "labelvalue", "query": "thanos-compactor" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(thanos_build_info, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Thanos Compact", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operations/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_tsdb_compactions_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace)",
     "legendFormat": "compaction {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{$labelselector=\"$labelvalue\"}[$interval])) by (pod)",
     "legendFormat": "bucket ops {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_compact_garbage_collection_total{$labelselector=\"$labelvalue\"}[$interval])) by (pod)",
     "legendFormat": "gc ops  {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_compact_group_compactions_total{$labelselector=\"$labelvalue\"}[$interval])) by (pod)",
     "legendFormat": "group compact  {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_compact_sync_meta_total{$labelselector=\"$labelvalue\"}[$interval])) by (pod)",
     "legendFormat": "sync metas  {{pod}}"
    }
   ]
  },
  {
   "title": "Operation Failures/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_failed_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace)",
     "legendFormat": "compaction {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_failures_total{$labelselector=\"$labelvalue\"}[$interval])) by (pod)",
     "legendFormat": "bucket ops {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_compact_garbage_collection_failures_total{$labelselector=\"$labelvalue\"}[$interval])) by (pod)",
     "legendFormat": "gc ops  {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_compact_group_compactions_failures_total{$labelselector=\"$labelvalue\"}[$interval])) by (pod)",
     "legendFormat": "group compact  {{pod}}"
    },
    {
     "expr": "sum(rate(thanos_compact_sync_meta_failures_total{$labelselector=\"$labelvalue\"}[$interval])) by (pod)",
     "legendFormat": "sync metas  {{pod}}"
    }
   ]
  },
  {
   "title": "Operation Time Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_compact_garbage_collection_duration_seconds_bucket{$labelselector=\"$labelvalue\"}[$interval])) by (pod,le))",
     "legendFormat": "99.99 gc {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_compact_sync_meta_duration_seconds_bucket{$labelselector=\"$labelvalue\"}[$interval])) by (pod,le))",
     "legendFormat": "99.99 sync meta  {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{$labelselector=\"$labelvalue\"}[$interval])) by (pod,le))",
     "legendFormat": "99.99 bucket ops {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(prometheus_tsdb_compaction_duration_seconds_bucket{$labelselector=\"$labelvalue\"}[$interval])) by (pod,le))",
     "legendFormat": "99.99 compact {{pod}}"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod_name=\"thanos-compactor-temp-0\"})",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{$labelselector=\"$labelvalue\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{$labelselector=\"$labelvalue\", quantile=\"1\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}