apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: node-exporter 
          resources:
            requests:
              cpu: 5m
              memory: 5Mi
            limits:
              memory: 100Mi
      nodeSelector:
