apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
    thanos: sidecar
    team: devops
  name: prometheus-sidecar
  namespace: monitoring
spec:
  ports:
    - port: 10901
      protocol: TCP
      targetPort: grpc
      name: grpc
    - port: 10902
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: prometheus
    prometheus: k8s
  type: NodePort