apiVersion: v1
kind: Service
metadata:
  name: logstash-cluster
  namespace: logging
spec:
  selector:
    app: logstash
  ports:
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: beats
  type: ClusterIP
